let musicNav = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]
let musicNav = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]
let musicNav = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]
let musicNav = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]




let musicCoverVersion = [
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"唱半首君に届け祝大家中秋节快乐",urls:"https://b23.tv/BV1UL411W7Mn"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"柠檬头的『身骑白马』 ♪(´∪`●)ゝ",urls:"https://b23.tv/BV1VL411x7at"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"怪物（YOASOBI）／まふまふ【歌ってみた】",urls:"https://b23.tv/BV1z64y1o7Zn"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"My Only One-Sebastian Yatra翻唱&吉他教程|C调&G调简单版|Cover",urls:"https://b23.tv/BV1Sf4y1a7c6"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"【春猿火】日文翻唱《不埒な喝采/不羁的喝彩》",urls:"https://b23.tv/BV1Rv411w7o1"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"这识别的准？",urls:"https://b23.tv/BV1sQ4y1975A"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"【2020超级大串烧】50多首歌一口气唱完，你听过几首？",urls:"https://b23.tv/BV1rf4y1B72G"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"《梵高先生》—好好生活比什么都强。",urls:"https://b23.tv/BV1nU4y1W7rE"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"风吹麦浪",urls:"https://b23.tv/BV1rL4y1a7bo"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"我猜你们喜欢看这个...",urls:"https://b23.tv/BV123411z7TL"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"【阿梓歌】《海海海》！！！纯享版！",urls:"https://b23.tv/BV1Z54y1V75r"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/0.jpg",title:"导 管 之 王",urls:"https://b23.tv/BV12341127Mw"},
    
]
let musicCoverVersionTwo = [
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"普通人在ktv唱《枫》有多撕心裂肺",urls:"https://b23.tv/BV1yh411n7cw"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"艾蜜莉wu艾蜜莉～",urls:"https://b23.tv/BV1b64y187Ae"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"50年到00年最火的月亮歌，你会唱几首？",urls:"https://b23.tv/BV1xf4y1E7dq"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"If I were a... Boyfriend (Robynn & Kendy) - Bieber x Beyonce Cover",urls:"https://b23.tv/BV1ku411f7GM"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"原神好声音 《关于我明明是翻唱却是人生中第一次剪视频这件事》",urls:"https://b23.tv/BV1gM4y137to"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"自娱自乐学粤语《少女的祈祷》",urls:"https://b23.tv/BV1DL411W7dP"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"【飞天小猪动漫协会】千里邀月 翻唱【双音部】",urls:"https://b23.tv/BV1uP4y1a7mD"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"Knockin on heavens door,",urls:"https://b23.tv/BV1BM4y137By"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"【A型】踊",urls:"https://b23.tv/BV19L4y187JY"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"城里的月光 (新版) - 王梓琪『城里的月光把梦照亮 请温暖他心房』（动态歌词/Lyrics Video）",urls:"https://b23.tv/BV1A34y1D7Ze"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"《欢》—苏琛    中秋快乐，祝大家被月饼吃掉",urls:"https://b23.tv/BV1Jb4y117dm"},
    {src:"bil_app/blblKoa/public/images/musicCoverVersion/musicCoverVersionTwo/0.jpg",title:"“中秋你注定一人”  吉他弹唱cover",urls:"https://b23.tv/BV1ob4y1y7Dr"},
    
]
let musicCoverVersionPhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicElectro_tone = [
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"DustDustDust!Former Time Trio—— Experienced Is Never Too Much",urls:"https://b23.tv/BV1Sh411p7D4"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【Phut Hot完整版】音量调节重置版2.0（音质也改好）",urls:"https://b23.tv/BV1eA411H7oM"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"震惊！小伙居然把《Stay》变成了超燃电音?!!!",urls:"https://b23.tv/BV17341167aD"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【Sc!AmersrgCall】Die In The Battle 战死沙场（Soyier_Tedd）",urls:"https://b23.tv/BV1ZT4y1P7xd"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"盘点那些UT同人的神曲！超好听的审判曲合集！（持续更新到32P）",urls:"https://b23.tv/BV1yq4y1p7Qf"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【全兽出击/同人曲】新曲预告！『十泉浩』角色同人曲",urls:"https://b23.tv/BV1xf4y1P7LE"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"烟鬼神曲Honest伴奏",urls:"https://b23.tv/BV1Sy4y1377B"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"我建了一个电子音乐资源分享交流网站！完全免费！！！",urls:"https://b23.tv/BV1oU4y1j76s"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【妄想症Paranoia】NOVA_扒谱",urls:"https://b23.tv/BV1xf4y1H7HN"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【ᴀᴠɪᴄɪɪ】假如..《STAY》是A神制作的电音..燃起来了（付免费工程⚡伪现场版）",urls:"https://b23.tv/BV1Gq4y1T7kP"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"【日推电音】Synymata,Zack Gray - Hard Not To Let You Go",urls:"https://b23.tv/BV16b4y1m7Eu"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/0.jpg",title:"spasmodic，但是是Future Bass",urls:"https://b23.tv/BV1H34116745"},
]
let musicElectro_toneTwo = [
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"Avicii音乐进化史（3）【2014-2020】",urls:"https://b23.tv/BV1zq4y1o7Ms"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"【Zxkav】vol.4+4.5",urls:"https://b23.tv/BV1BL4y187ki"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"【熟肉】Mesto编曲（一）写旋律",urls:"https://b23.tv/BV1gR4y1p7AL"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"【4K】David Guetta塔叔超清现场！Top100DJs 虚拟音乐节 2021",urls:"https://b23.tv/BV1f44y1b7ri"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"Altrinkce remix SUNRISE AND UNITY",urls:"https://b23.tv/BV1qM4y137uC"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"交作业2",urls:"https://b23.tv/BV1cQ4y1C7bh"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"【ParE】挑战最快手速玩Push2和魔方——今天的月饼 你吃了嘛？",urls:"https://b23.tv/BV1JR4y1p7Yc"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"中秋国潮live",urls:"https://b23.tv/BV1y44y1b7Ah"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"NEOtabi纯音乐，无任何噪音！",urls:"https://b23.tv/BV1c64y187QH"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"[Free]油管超高质量付费Future Bounce采样包[Serum sylenth1 presets FLP++]",urls:"https://b23.tv/BV1gP4y1a7H2"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"【音乐制作工坊】用手机编曲软件能制作 中秋神曲？",urls:"https://b23.tv/BV1X44y1b7JS"},
    {src:"bil_app/blblKoa/public/images/musicElectro_tone/musicElectro_toneTwo/0.jpg",title:"《不要把音乐强行转midi》",urls:"https://b23.tv/BV1rL4y1872S"},
]
let musicElectro_tonePhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicLive = [
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"许巍《曾经的你》现场版。每一次难过的时候，就独自看一看大海。",urls:"https://b23.tv/BV1yf4y137Xh"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【中字直拍】超清横屏近脸 穿成这样也难掩柳姐美貌 aespa - 'Black Mamba' (KARINA/柳智敏)",urls:"https://b23.tv/BV1wy4y1U76D"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【布兰妮早期现场】【高糊预警】世界上再也没有比小甜甜布兰妮更甜美的女歌手",urls:"https://b23.tv/BV1eQ4y1y73y"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"經典粵語發燒金曲《偶遇》願各位老友人月兩團圓",urls:"https://b23.tv/BV1Hq4y1f7sH"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【促贩】DOKONJOFINGER LIVE",urls:"https://b23.tv/BV11b4y117JB"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"宋祖儿上声乐课唱羞答答的玫瑰静悄悄的开",urls:"https://b23.tv/BV1sv411P7uh"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"SUNNY DAY SONG ——内田彩 20210911 Character Song Live",urls:"https://b23.tv/BV1j34y1Q7UY"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"碧梨巴萨诺瓦 TIME100 最新不插电现场",urls:"https://b23.tv/BV1sL4y187tw"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【晋江一中七音乐队×学生会】用《不为谁而作的歌》的方式打开教师节!",urls:"https://b23.tv/BV1j3411q7hf"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【aespa】Next Level柳智敏直拍 人气歌谣回归舞台 4K超清细节(Inkigayo 210530)",urls:"https://b23.tv/BV1a5411g7aY"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【4K重置.Live'91】Beyond《灰色轨迹》巅峰双吉他！",urls:"https://b23.tv/BV1tq4y1M7ji"},
    {src:"bil_app/blblKoa/public/images/musicLive/0.jpg",title:"【4K60FPS】蕾哈娜Rihanna《Diamonds》维密现场！气场全开！",urls:"https://b23.tv/BV1Wv411P7tt"},

]
let musicLiveTwo = [
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"周深《触不可及》",urls:"https://b23.tv/BV1Gb4y117ik"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"【赵氏孤儿】音乐剧  晋国公主对孤儿所唱段：你是谁～",urls:"https://b23.tv/BV1xf4y1w764"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"Rammstein LIVE - 1998.10.30 - Nassau Coliseum, Uniondale, New York, USA FULL",urls:"https://b23.tv/BV1o44y1b7mg"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"存",urls:"https://b23.tv/BV1JL41147SA"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"D17R4PNT LIVE at MAO in GZ",urls:"https://b23.tv/BV1Fg411w7CD"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"Take Louder，Take Louder，Take Louder！",urls:"https://b23.tv/BV1kP4y1h79T"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"为已故婴儿的帕凡舞曲“莫里斯·拉威尔，爱丽丝-萨拉·奥特",urls:"https://b23.tv/BV1vq4y1P7ZJ"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"小红帽和大灰狼",urls:"https://b23.tv/BV1kf4y1E7a1"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"现在发I  am  not  cool应该不会有人看吧",urls:"https://b23.tv/BV11Q4y1z7eP"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"瓦格纳 罗恩格林 在遥远的地方 Roberto Alagna",urls:"https://b23.tv/BV1E34y1D7Jy"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"2021-9-16虎牙【阿难】直播回放",urls:"https://b23.tv/BV16U4y1A7x6"},
    {src:"bil_app/blblKoa/public/images/musicLive/mmusicLiveTwo/0.jpg",title:"椅子2021.8.15昆明《手捧一杯酒》",urls:"https://b23.tv/BV1wf4y1A77o"},
]
let musicLivePhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicMV = [
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"泫雅+金晓钟 情侣组队出道曲PING PONG MV+打歌舞台合集(更至210919)",urls:"https://b23.tv/BV1nb4y127i8"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"酷玩乐队Coldplay - Yellow｜官方MV【中英歌词】",urls:"https://b23.tv/BV1QL411x7Uz"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【Mono Inc.】Risk It All",urls:"https://b23.tv/BV1nv411E7aV"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【Sunny】夏日最后的狂欢",urls:"https://b23.tv/BV1gL4y1v7Hc"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【ずっと真夜中でいいのに。】ばかじゃないのに（明明不是笨蛋）【MV／中文字幕】【MAPPA『10th Anniversary Movie』联动乐曲】",urls:"https://b23.tv/BV1RX4y1c7Bj"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"幻影忍者十周年mv",urls:"https://b23.tv/BV1WV411E7Hg"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"MAISONdes&和ぬか&asmi「ヨワネハキ」",urls:"https://b23.tv/BV1M44y1675d"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"[中字] 像Jaden这样深情的男孩很难不爱Jaden-We Were Fifteen",urls:"https://b23.tv/BV1kM4y137yg"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【烟鬼组合】我们参与混音的《Don't Say》发行四周年了！一起来再听下吧！",urls:"https://b23.tv/BV15M4y1M7t6"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【混剪】150秒看完beyond放暑假！",urls:"https://b23.tv/BV1A34y1X7JA"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"2021年抖音好听的歌曲,超火《心若向阳》,经典，太好听了,动听!",urls:"https://b23.tv/BV1R54y1L7ws"},
    {src:"bil_app/blblKoa/public/images/musicMV/0.jpg",title:"【Reol】 「白夜」(白夜極光オリジナルアニメ・ヴァージョン)",urls:"https://b23.tv/BV1yf4y187Fh"},
 
]
let musicMVTWo = [
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"许艺娜《Happiness》",urls:"https://b23.tv/BV1bf4y1E7qi"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"日向坂46『夢は何歳まで？』",urls:"https://b23.tv/BV1c44y1873t"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"[Official Music Video] Perfume 「ポリゴンウェイヴ」官方繁体中字版",urls:"https://b23.tv/BV1Yf4y1w7cJ"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"NiziU - Take a picture (舞蹈红衣版) (4K)",urls:"https://b23.tv/BV1tu411f7uw"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"毁灭吧世界",urls:"https://b23.tv/BV1rL4y187yb"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"Gris - Il Etait Une Forêt【full】",urls:"https://b23.tv/BV1xU4y1A7Z2"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"Soler《风的季节》MV (仿制：TVB点藏点乐)",urls:"https://b23.tv/BV17q4y1o7nB"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"杨钰莹。中秋快乐，月亮船。",urls:"https://b23.tv/BV1vh411n7z6"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"青空のラプソディ（スーパーちょろゴンず ver.）MV+Making",urls:"https://b23.tv/BV1DL411W7K1"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"【请戴上耳机】Alec Benjamin - Let Me Down Slowly - 24D高音质音乐+MV",urls:"https://b23.tv/BV1df4y1w7ow"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"9999 之后会发生什么？",urls:"https://b23.tv/BV1vb4y1y72J"},
    {src:"bil_app/blblKoa/public/images/musicMV/musicMVTwo/0.jpg",title:"舞蹈不错",urls:"https://b23.tv/BV1HR4y1p7jr"},
]
let musicMVPhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicOriginal = [
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"暗 潮 汹 涌，LASER四子你争我夺，开启西幻大陆权谋冒险！",urls:"https://b23.tv/BV1kp4y1r7Ck"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【夏小桐】【少年弦】初到B站，一首少年弦送给大家",urls:"https://b23.tv/BV1M54y167nn"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"遊生夢死 (Yuseiboushi)  - Eve MV",urls:"https://b23.tv/BV1Th411p7jY"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【五音Jw】全新改编《相思门》|  我本非天生情种  痴心不怕人笑我懵懂",urls:"https://b23.tv/BV1jg411V7ko"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"“偶像”",urls:"https://b23.tv/BV1u64y1v7oU"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【墨香铜臭开文七周年贺曲】写给我最爱的卖花女孩",urls:"https://b23.tv/BV1u44y1b7yG"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【Vicky宣宣】我又来整活啦哈哈哈哈",urls:"https://b23.tv/BV1i64y1e79x"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【萨顶顶 X ilem 原创】《斩草歌》震撼合作究极上头，斩妖念诵与教主的惊喜碰撞",urls:"https://b23.tv/BV1Lw411d7vS"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"又温柔又御的女侠你会喜欢吗？——仗剑行【余音社/毛茸茸Moral】",urls:"https://b23.tv/BV1HK4y1H7Q8"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【京腔小曲】中阮弹唱京剧《斩萧何》之【清江引】-“萧何三次曾保荐”-",urls:"https://b23.tv/BV1Bq4y1K7dD"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:" 离谱！周杰伦新歌《橙色靴子国》？？？",urls:"https://b23.tv/BV1bP4y1a7fH"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/0.jpg",title:"【司南•三无】天光【原创曲】",urls:"https://b23.tv/BV1Vb4y1S7fz"},
]
let musicOriginalTwo = [
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"海呀海呀海",urls:"https://b23.tv/BV1mb4y1y7xr"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"盛不盛开，花都是花。旅行到第十七夜原创作品《花不开》",urls:"https://b23.tv/BV1JM4y137Vj"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"【星若】 钢琴曲 （长吟）  音 乐 频 道",urls:"https://b23.tv/BV1bq4y1o7uf"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"想起了密码，做了个demo。",urls:"https://b23.tv/BV1Fb4y117PQ"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"无",urls:"https://b23.tv/BV1aM4y137in"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"《不会笑》-2021-9-21",urls:"https://b23.tv/BV1Mb4y117YG"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"KDC-T审判曲：《问剧》",urls:"https://b23.tv/BV1cb4y117cA"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"农业说唱《超农业》",urls:"https://b23.tv/BV15M4y137jL"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"(库乐队)La la land-Jax",urls:"https://b23.tv/BV1A64y1873K"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"《clap of thunder》“不管你在哪儿，总有一道惊雷会劈散荒芜与黑暗”",urls:"https://b23.tv/BV1Q64y1b79P"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"【medly】第一次上传工程视频！！！",urls:"https://b23.tv/BV13q4y1P7ef"},
    {src:"bil_app/blblKoa/public/images/musicOriginal/musicOriginalTwo/0.jpg",title:"人生第一次！写的歌被神仙民乐演奏！绝了啊啊啊v",urls:"https://b23.tv/BV1FU4y1A7rQ"},
]
let musicOriginalPhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicPlay = [
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【宇多田光】 One Last Kiss EVA终章新曲 小提琴版",urls:"https://b23.tv/BV1bU4y1p71K"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"on my own 有为青年 吉他 cover",urls:"https://b23.tv/BV18q4y1D7m8"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"《KING》为了练这首我差点把钢琴砸坏了｜特效钢琴",urls:"https://b23.tv/BV1gP4y1h7Dz"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"《蒲公英的约定》钢琴教学简易版改编双手钢琴简谱教程来咯！完整版已完成！",urls:"https://b23.tv/BV1U44y1b7sK"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【二胡 cover】水调歌头｜中秋快乐",urls:"https://b23.tv/BV1hL4y1a7xB"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"20万taylor弹奏中秋节的祝福是一种什么体验？",urls:"https://b23.tv/BV14b4y1y7yK"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【萨克斯】Plastic Love 竹内玛莉亚， 我的努力 只需要你们一个小小的手指头动一下",urls:"https://b23.tv/BV1QA411F739"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【Mr.Li 钢琴】 《一花一剑》 为你明灯三千，为你花开满城",urls:"https://b23.tv/BV1Ct4y1a72D"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【钢琴】《C大调前奏曲 BWV846》",urls:"https://b23.tv/BV1aK411g7TE"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"【指弹吉他】完美还原梁博《出现又离开》，4.22秒震撼你的听觉！",urls:"https://b23.tv/BV1Y5411T72Y"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"进 祭 的 巨 人",urls:"https://b23.tv/BV13A41147mP"},
    {src:"bil_app/blblKoa/public/images/musicPlay/0.jpg",title:"水の声《卡农》超治愈～",urls:"https://b23.tv/BV1bq4y1f7PC"},
]
let musicPlayTwo = [
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"《广寒宫》笛子独奏",urls:"https://bili2233.cn/BV1fb4y1y7E1"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"【陶笛】大鱼   曲降e调，降b陶笛f指法",urls:"https://bili2233.cn/BV1pR4y1p7KB"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"拜厄No.74练习",urls:"https://bili2233.cn/BV1F64y187F3"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"C.Debussy___Clair de Lune (Nakju Choi)",urls:"https://bili2233.cn/BV1FP4y1a7KB"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"8、《自新大陆》第二乐章（德沃夏克）#成人钢琴#飘落在琴键上的叶子",urls:"https://bili2233.cn/BV18f4y1E7Qb"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"【零基础钢琴】大神都是怎么做到自学成才的？我觉得真的好难，求赐教！",urls:"https://bili2233.cn/BV14M4y1379q"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"卡西欧电子琴ct200和口风琴的合奏《繁花》三生三世十里桃花插曲",urls:"https://bili2233.cn/BV1e44y1b79C"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"罗兰-15KV",urls:"https://bili2233.cn/BV1JR4y1p7Qw"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"中秋复读《暧昧》电吉他改编",urls:"https://bili2233.cn/BV1Av411G7zv"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"「像神一样呐」钢琴版（b站首发？",urls:"https://bili2233.cn/BV1hu411f7bw"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"【笛子】 《但愿人长久》 千里共婵娟 中秋快乐！",urls:"https://bili2233.cn/BV1564y187gQ"},
    {src:"bil_app/blblKoa/public/images/musicPlay/musicPlayTwo/0.jpg",title:"【你的绵绵钢琴】《游山恋》",urls:"https://bili2233.cn/BV1Z64y1b7D9"},
]
let musicPlayPhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicSynthesize = [
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"收藏夹必存！《唱歌教程全集》小白学唱歌必看声乐基础/唱歌技巧/乐理/腹式呼吸/发声方法全套课程",urls:"https://b23.tv/BV1ob4y1U7af"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"为Diss偶像道歉！AK刘彰《道歉信》-《创造营》的舞台表现",urls:"https://b23.tv/BV1eK4y1Q7kr"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"【全程高能】赌一个赞~答对一半算我输！ ！",urls:"https://b23.tv/BV1Bq4y1Z7x9"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"东百红日MV",urls:"https://b23.tv/BV1sL4y1a79w"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"【Blob Opera x 东方】系列，持续更新（71P）",urls:"https://b23.tv/BV1k44y187np"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"「阳炎Project」十周年纪念PV《Children Record  Re:boot》公开!",urls:"https://b23.tv/BV1oB4y1P7sW"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"26首燃爆全球的动漫神曲现场版！BGM一响，每个男人都会狼血沸腾！",urls:"https://b23.tv/BV1WM4y1G7cU"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"【睡眠风景】可不可以跟世界请个假，我想暂时离开下。",urls:"https://b23.tv/BV1aQ4y1r7pb"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"【说唱听我的2 第五期】CSC 大战 CDC/ 刘聪VS谢帝",urls:"https://b23.tv/BV1Do4y1U7u1"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"【A-SOUL/云南山歌】汤姆和乃琳山歌对唱，场面过于逆天！",urls:"https://b23.tv/BV1Zf4y1E7XG"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"我以为我可以跟得上墨曲… 这段我练过…",urls:"https://b23.tv/BV17P4y1Y7Xj"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/0.jpg",title:"豫剧《穆桂英挂帅》——选段马金凤——辕门外三声炮如同雷震",urls:"https://b23.tv/BV1LP4y1W7Mc"},
]
let musicSynthesizeTwo = [
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"要是非得什么都会了才能练即兴solo，这辈子怕是都来不及练即兴，因为知识无止尽啊",urls:"https://b23.tv/BV1AQ4y1C7No"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"#叕唐鼓手学院# 深圳 #Syncopation# 1-3 六连音拓展 BPM-75@鼓手唐剑波 @Drummer杨奎 @Drummer茜子",urls:"https://b23.tv/BV1FP4y1a7uD"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"鼎盛王朝康熙大典实景演出",urls:"https://b23.tv/BV1Hh411n7kK"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"【黄霄雲】回到好声音首唱新歌《带我去很远地方》",urls:"https://b23.tv/BV1B44y1b7Lf"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"「情歸於盡」黎明",urls:"https://b23.tv/BV1h3411278d"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"李翠翠 Bard 人生如戏 伴奏 beat 高品质无人声",urls:"https://b23.tv/BV1EL4y187Rb"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"河北梆子辕门斩子-戴乌纱好一似愁人的帽（王玉罄）",urls:"https://b23.tv/BV1Cv41137Ys"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"上海1943（“外滩“真声噩梦）",urls:"https://b23.tv/BV12U4y1A7XJ"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"好听的音乐【放松一下】",urls:"https://b23.tv/BV1JU4y1A7oa"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"机智的医生生活BGM剪辑(乐队版&OST&伴奏版)",urls:"https://b23.tv/BV1eL4y187vL"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"好听的歌曲《Под фонарем》",urls:"https://b23.tv/BV1FQ4y1C7H8"},
    {src:"bil_app/blblKoa/public/images/musicSynthesize/musicSynthesizeTwo/0.jpg",title:"与音乐相伴 俯瞰美丽的世界 --- Oregon",urls:"https://b23.tv/BV1A3411m79X"},
]
let musicSynthesizePhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]

let musicVocaloid = [
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【乐正绫原创】赌徒|赌上人生十年，也不曾胜天半子",urls:"https://b23.tv/BV1u44y1b71H"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"命运讲述了什么故事?春卷饭的世界观有多宏大?个人解析命运剧情",urls:"https://b23.tv/BV1L64y1Y7yN"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【初音未来V4C】复制品【諾 x tuikk】",urls:"https://b23.tv/BV1o341127dw"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【洛天依原创】饿魔烧酒",urls:"https://b23.tv/BV1pU4y1771r"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【洛天依原创曲】星陨花【一体机制作】",urls:"https://b23.tv/BV1P34y1X7ZS"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"工团天下(权御AI特供粉丝自制版）",urls:"https://b23.tv/BV1og411G7kK"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【可不】有好好的哦【傘村トータ】",urls:"https://b23.tv/BV1G34y1X7AL"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【贾诩】木兰行翻填（字虽文和，谋致乱武）",urls:"https://b23.tv/BV1Ji4y1P7YS"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【刻晴】热爱105°C的牛杂",urls:"https://b23.tv/BV16g411g7pr"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【Earth Square】八王子P - RAD DOGS - 【VOCALOID x6】(2DMV) (Cover)",urls:"https://b23.tv/BV1Db4y127oS"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【改词】勾指起誓 化学竞赛版（化学竞赛也是可以甜起来的嘛）",urls:"https://b23.tv/BV1vQ4y117Gv"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/0.jpg",title:"【Oliver原创曲】bandage",urls:"https://b23.tv/BV1m54y1h76x"},
]
let musicVocaloidTwo = [
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【赤羽翻调】里德万岁",urls:"https://b23.tv/BV1ZQ4y1r7G7"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"#中秋节快乐 给大家献一首周杰伦的《青花瓷》",urls:"https://b23.tv/BV1ZQ4y1k7yV"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【洛天依原创】望夜",urls:"https://b23.tv/BV1Vq4y1o7q1"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"PARANOIA LOST / 来世は鯨になりたい feat.初音ミク",urls:"https://b23.tv/BV14L41147pk"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【孙枫】《慕容》（翻自：河图）祝大家中秋团圆嗷~",urls:"https://b23.tv/BV1d44y1b7r8"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"这就是抖音吗？谢谢 吐了",urls:"https://b23.tv/BV1QL411W7ee"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"没未来，没期待，也没了你",urls:"https://b23.tv/BV1ZL411x7zC"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【洛天依粤语翻唱】半斤八两『过气歌姬沦落黑厂打工，提桶跑路被资本家当场抓获』",urls:"https://b23.tv/BV1Sb4y1y7cz"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【flower】pawn【つくの】",urls:"https://b23.tv/BV1Yu411f7zH"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【洛天依/乐正绫/言和】爱出发",urls:"https://b23.tv/BV1qu411f71p"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"【初音ミク】PARANOIA LOST【来世は鯨になりたい】",urls:"https://b23.tv/BV1944y1b7tW"},
    {src:"bil_app/blblKoa/public/images/musicVocaloid/musicVocaloidTwo/0.jpg",title:"夕山谣【ACE虚拟歌姬！",urls:"https://b23.tv/BV1E44y1b7Bq"},
]
let musicVocaloidPhb = [
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
    {src:"",title:"",urls:""},
]